# Doing a Linear regression without Scikit Learn

There's nothing better to understand the gradient descent algorithm than to code it from scratch. It may seem difficult at first glance but don't worry, we will guide you step by step. It is also a fantastic occasion to practice python key concepts like **Classes**!

Don't hesitate to come back to your Machine Learning course on linear regression to refresh your memory. 

Our goal will be to code a simple linear regression such as : 

$f(x) = \beta_1 \times x + \beta_0$

* Import the following libraries: 
  * Numpy 

In [ ]:
import numpy as np 

* Define a `Model` class that will take two methods: 
  1. `__init__(self)`, the class builder which will allow you to define an attribute $\beta_0$ (`beta_0` in your code) and an attribute $\beta_1$ (`beta_1` in your code). These attributes represent the coefficients/parameters of the model an we will be initialize them randomly using Numpy (cf: `np.random.randn`).
  2. `__call__(self, x)`, a special method that will turn our class into a callable which will return $\beta_1 \times x + \beta_0$ when called.

In [ ]:
class Model():
  def __init__(self):
    self.beta_1 = np.random.randn(1)
    self.beta_0 = np.random.randn(1)
  
  def __call__(self, x):
    return self.beta_1 * x + self.beta_0

* Create an instance of your class `Model`

In [ ]:
model = Model()

In [ ]:
model.beta_0

array([-0.41664214])

In [ ]:
model.beta_1

array([0.38650821])

* Try doing a first "regression" by running `model(3.0)`. 
NB: If you don't have the same values as this notebook in output, this is normal since you have initialized your values randomly. 

In [ ]:
model(3.0)

array([0.74288249])

In [ ]:
model.beta_1 * 3 + model.beta_0

array([0.74288249])

* This value corresponds to a random prediction of your model. But we don't have any data yet. This time, let's use `sklearn` to import data. 
  * Import `sklearn.datasets`
  * Use the `load_diabetes()` function to load the diebetes dataset in an object called `diabetes`.
  * Print the `DESCR` attribute of the diabetes object
  * Save the content of the `data` attribute in an object named `diabetes_data`
  * Save the content of the `target` attribute in an object named `y`

In [ ]:
from sklearn import datasets, linear_model

# Load the diabetes dataset
diabetes = datasets.load_diabetes()
print(diabetes.DESCR)
diabetes_data = diabetes.data
y = diabetes.target

.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - Age
      - Sex
      - Body mass index
      - Average blood pressure
      - S1
      - S2
      - S3
      - S4
      - S5
      - S6

Note: Each of these 10 feature variables have been mean centered and scaled by the standard deviation times `n_samples` (i.e. the sum of squares of each column totals 1).

Source URL:
https://www4.stat.ncsu.edu/~boos/var.select/diabetes.html

For more information see:
Bra

* We have too much data in this dataset `diabetes_data`, take only the third column of the dataset and store it in a `diabetes_X` variable.

In [ ]:
# Use only one feature
diabetes_X = diabetes_data[:,2]
diabetes_X[:5]

array([ 0.06169621, -0.05147406,  0.04445121, -0.01159501, -0.03638469])

* Visualize your data using `plotly`.

In [ ]:
import plotly.express as px
fig = px.scatter(x= diabetes_X, y=y, title="Scatter plot of BMI against Diabetes metric",
                 labels={
                     "x": "BMI",
                     "y": "Diabtes Metric"
                 })
fig.show()
"""import matplotlib.pyplot as plt 
plt.scatter(diabetes_X, y)
plt.xlabel(diabetes.feature_names[2])
plt.ylabel("target")
plt.show()"""

'import matplotlib.pyplot as plt \nplt.scatter(diabetes_X, y)\nplt.xlabel(diabetes.feature_names[2])\nplt.ylabel("target")\nplt.show()'

* Now we need to define a cost function. For a linear regression, we could use MSE :

`np.mean((model(input) - y)**2)`

  * Create this function which we'll call `mse` (for mean square error). This function will take two arguments `y_pred` & `y_true`.

In [ ]:
def mse(y_pred, y_true):
  # return (np.sum((y_pred - y_true)**2))/len(y_pred) alternate solution
  return np.mean((y_pred - y_true)**2) # it is important to use numpy functions
  # since they can be applied easily on numpy arrays (or array like objects)
  # and they compute very fast compared to pure python operations

* Test your function by inserting `model(diabetes_X)` & `y` as arguments. 
* Calculate the rmse as well

In [ ]:
print("MSE : ",mse(model(diabetes_X), y))
print("RMSE : ",np.sqrt(mse(model(diabetes_X), y)))

MSE :  29199.765798314576
RMSE :  170.8793896241281


* Visualize your regression in relation to your points 

In [ ]:
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(x=diabetes_X, y=y,
                    mode='markers',
                    name='target'))
fig.add_trace(go.Scatter(x=diabetes_X, y=model(diabetes_X),
                    mode='lines',
                    name='predictions'))
fig.update_layout(
    title="Target vs Predictions",
    xaxis_title="BMI",
    yaxis_title="Diabetes metric"
    )
fig.show()

* We're going to need to compute the gradients for our variable `model.beta_1` and our constant `model.beta_0`. To do this, we're going to need to review our derivative formulas. Since we're not here to do math, we're going to give you these formulas. 
  * `derive_model_beta_1 = 2/len(y_pred)*np.sum((x @ (y_pred - y_true)))`
  * `derive_model_beta_0 = 2/len(y_pred)*(np.sum(y_pred - y_true))`

  * Feel free to read this article if you want to know more about the calculation of the derivative: [Gradient Descent Derivation](https://mccormickml.com/2014/03/04/gradient-descent-derivation/)


  * So using the above formulas, code the first function `derivative_mse_beta_1` that will take the arguments: 
    * `x` --> the values for your variable / `y_pred` --> the values predicted by your model / `y_true` --> the values of the target variable


In [ ]:
# Calculate model.beta_1's derivate
def derivative_mse_beta_1(y_pred, y_true, x):
  return 2/len(y_pred)*np.sum((x @ (y_pred - y_true)))
  # return 2/len(y_pred) * np.sum(np.dot(x,(y_pred-y_true)))

* Test you function

In [ ]:
derivative_mse_beta_1(model(diabetes_X), y, diabetes_X)

-4.294338245128697

* So using the above formulas, now code the `derivative_mse_beta_0` function which will take the arguments :
    * `y_pred` --> the values predicted by your model / `y_true` --> the actual values to predict

In [ ]:
# Calculate model.b's derivate
def derivative_mse_beta_0(y_pred, y_true):
  return 2/len(y_pred)*(np.sum(y_pred - y_true))

* Test you function

In [ ]:
derivative_mse_beta_0(model(diabetes_X), y)

-305.1002526146343

* We will try to see if we can minimize our cost function using the two gradients above. To update our variables, we need to subtract their respective gradients. Ex: 
  * `param = param - learning_rate * gradient`

  * Set a `learning_rate` to 0.1
  * Try to apply your formula on `model.beta_1` and `model.beta_0`.

In [ ]:
lr = 0.1

print("OLD model.a = {}".format(model.beta_1))
print("OLD model.b = {}".format(model.beta_0))

model.beta_1 -= lr * derivative_mse_beta_1(model(diabetes_X), y, diabetes_X)
# model.a = model.a - lr * derivative_mse_a(model(diabetes_X), y, diabetes_X)
model.beta_0 -= lr * derivative_mse_beta_0(model(diabetes_X), y)

print("NEW model.a = {}".format(model.beta_1))
print("NEW model.b = {}".format(model.beta_0))

OLD model.a = [0.38650821]
OLD model.b = [-0.41664214]
NEW model.a = [0.81594204]
NEW model.b = [30.09338312]


Wesee that the values of the two parameters have changed, let's see how it affected the predictions of the model. 
Visualize the data vs the model's predictions.

In [ ]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=diabetes_X, y=y,
                    mode='markers',
                    name='target'))
fig.add_trace(go.Scatter(x=diabetes_X, y=model(diabetes_X),
                    mode='lines',
                    name='predictions'))
fig.update_layout(
    title="Target vs Predictions",
    xaxis_title="BMI",
    yaxis_title="Diabetes metric"
    )
fig.show()

We notice the predictions got a little closer to our real data
* Recalculate your MSE

In [ ]:
mse(model(diabetes_X), y)

20820.1673083469

* Our MSE has dropped a lot! This is good news but the process of gradient descent is iterative. So you'll have to do it several times before arriving at accurate predictions. 
  * By making a loop, try to repeat the process from above 10,000 times. 
  * Display every 1000 epochs: mse, model.beta_1 & model.beta_0 

In [ ]:
# Define learning rate and a number of iterations 
lr = 0.1
epochs = 10000

In [ ]:
model = Model()
for epoch in range(epochs):
  # Calculate the loss function
  current_loss = mse(model(diabetes_X), y)
  
  # Update variables
  model.beta_1 -= lr * derivative_mse_beta_1(model(diabetes_X), y, diabetes_X)
  model.beta_0 -= lr * derivative_mse_beta_0(model(diabetes_X), y)

  # Show updated variables
  if epoch % 1000 == 0 or epoch == epochs - 1:
    print("-------------------- Epoch {} --------------------".format(epoch))
    print("Current Loss: {}".format(current_loss))
    print("beta_1 = {}".format(model.beta_1))
    print("beta_0 = {}".format(model.beta_0))

-------------------- Epoch 0 --------------------
Current Loss: 29214.856625242403
beta_1 = [-1.8063269]
beta_0 = [30.08339534]
-------------------- Epoch 1000 --------------------
Current Loss: 4719.232033282504
beta_1 = [344.46640766]
beta_0 = [152.13348416]
-------------------- Epoch 2000 --------------------
Current Loss: 4225.669891599262
beta_1 = [564.68829636]
beta_0 = [152.13348416]
-------------------- Epoch 3000 --------------------
Current Loss: 4026.0397049990993
beta_1 = [704.7446029]
beta_0 = [152.13348416]
-------------------- Epoch 4000 --------------------
Current Loss: 3945.295644552924
beta_1 = [793.81735185]
beta_0 = [152.13348416]
-------------------- Epoch 5000 --------------------
Current Loss: 3912.637240489043
beta_1 = [850.46567279]
beta_0 = [152.13348416]
-------------------- Epoch 6000 --------------------
Current Loss: 3899.427954875885
beta_1 = [886.49276643]
beta_0 = [152.13348416]
-------------------- Epoch 7000 --------------------
Current Loss: 3894.08

* Using `plotly`, view your model and actual values again

In [ ]:
fig = go.Figure()
fig.add_trace(go.Scatter(x=diabetes_X, y=y,
                    mode='markers',
                    name='target'))
fig.add_trace(go.Scatter(x=diabetes_X, y=model(diabetes_X),
                    mode='lines',
                    name='predictions'))
fig.update_layout(
    title="Target vs Predictions",
    xaxis_title="BMI",
    yaxis_title="Diabetes metric"
    )
fig.show()

**We've got a nice regression this time!** 